name: .NET Core (build)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v2.3.4
    - name: .NET core build
      uses: actions/setup-dotnet@v1.9.1
      with:
        dotnet-version: 6.0.100-preview.2.21155.3
    - name: Restore
      run: |
        dotnet nuget add source "https://api.nuget.org/v3/index.json" --name "nuget.org"
        dotnet restore
      shell: bash

    - name: Build with dotnet
      run: |
        dotnet build --configuration Release --no-restore
        dotnet pack --configuration Release --no-build
      shell: bash
